export const DEFAULT_ROOM_MODE = "conversation";
export const CONVERSATION_MAX_PARTICIPANTS = 2;
export const PRESENTATION_MAX_PARTICIPANTS = 20;
export const DEFAULT_MAX_PARTICIPANTS = CONVERSATION_MAX_PARTICIPANTS;
export const ROOM_CODE_LENGTH = 6;
